# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_id',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
