# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_id',
            field=models.CharField(max_length=250),
        ),
    ]
